import type { FamilyMember } from './types';

// Mock family for the demo. The account holder ("Ich") plus two children.
export const family: readonly FamilyMember[] = [
  {
    id: 'M-self',
    firstName: 'Anna',
    lastName: 'Schmid',
    dob: '1985-03-12',
    sex: 'F',
    relation: 'self',
    vaccinations: [
      { id: 'a1', disease: 'Diphtherie, Tetanus, Pertussis', vaccine: 'Boostrix', date: '2005-09-14', dose: 'Booster', manufacturer: 'GlaxoSmithKline', batch: 'BX0509', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a2', disease: 'Diphtherie, Tetanus, Pertussis', vaccine: 'Boostrix', date: '2015-11-04', dose: 'Booster', manufacturer: 'GlaxoSmithKline', batch: 'DT9923', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a3', disease: 'Masern, Mumps, Röteln', vaccine: 'MMR-VaxPro', date: '1986-04-18', dose: '1/2', manufacturer: 'MSD', batch: 'M2204X', route: 's.c.', site: 'Oberarm rechts' },
      { id: 'a4', disease: 'Masern, Mumps, Röteln', vaccine: 'MMR-VaxPro', date: '1992-08-25', dose: '2/2', manufacturer: 'MSD', batch: 'M5511Y', route: 's.c.', site: 'Oberarm rechts' },
      { id: 'a5', disease: 'Hepatitis B', vaccine: 'Engerix-B', date: '1998-01-12', dose: '1/3', manufacturer: 'GlaxoSmithKline', batch: 'HB1201', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a6', disease: 'Hepatitis B', vaccine: 'Engerix-B', date: '1998-02-15', dose: '2/3', manufacturer: 'GlaxoSmithKline', batch: 'HB1245', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a7', disease: 'Hepatitis B', vaccine: 'Engerix-B', date: '1998-08-10', dose: '3/3', manufacturer: 'GlaxoSmithKline', batch: 'HB1502', route: 'i.m.', site: 'Oberarm rechts' },
      { id: 'a8', disease: 'FSME', vaccine: 'FSME-Immun CC', date: '2012-04-02', dose: '1/3', manufacturer: 'Pfizer', batch: 'FS3301', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a9', disease: 'FSME', vaccine: 'FSME-Immun CC', date: '2012-05-30', dose: '2/3', manufacturer: 'Pfizer', batch: 'FS3344', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a10', disease: 'FSME', vaccine: 'FSME-Immun CC', date: '2013-03-12', dose: '3/3', manufacturer: 'Pfizer', batch: 'FS4012', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a11', disease: 'FSME', vaccine: 'FSME-Immun CC', date: '2023-04-19', dose: 'Booster', manufacturer: 'Pfizer', batch: 'FS9912', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a12', disease: 'COVID-19', vaccine: 'Comirnaty (BNT162b2)', date: '2021-05-21', dose: '1/2', manufacturer: 'Pfizer-BioNTech', batch: 'EW0150', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a13', disease: 'COVID-19', vaccine: 'Comirnaty (BNT162b2)', date: '2021-06-18', dose: '2/2', manufacturer: 'Pfizer-BioNTech', batch: 'FA2421', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a14', disease: 'COVID-19', vaccine: 'Comirnaty Omicron XBB.1.5', date: '2023-10-12', dose: 'Booster', manufacturer: 'Pfizer-BioNTech', batch: 'GH8821', route: 'i.m.', site: 'Oberarm rechts' },
      { id: 'a15', disease: 'Influenza (saisonal)', vaccine: 'Fluarix Tetra', date: '2024-10-08', dose: 'Saison 24/25', manufacturer: 'GlaxoSmithKline', batch: 'FLU2425', route: 'i.m.', site: 'Oberarm links' },
      { id: 'a16', disease: 'Influenza (saisonal)', vaccine: 'Fluarix Tetra', date: '2025-10-14', dose: 'Saison 25/26', manufacturer: 'GlaxoSmithKline', batch: 'FLU2526', route: 'i.m.', site: 'Oberarm links' },
    ],
  },
  {
    id: 'M-son',
    firstName: 'Luca',
    lastName: 'Schmid',
    dob: '2016-04-08',
    sex: 'M',
    relation: 'son',
    vaccinations: [
      { id: 's1', disease: 'Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B', vaccine: 'Infanrix hexa', date: '2016-06-14', dose: '1/3', manufacturer: 'GlaxoSmithKline', batch: 'IH1606', route: 'i.m.', site: 'Oberschenkel links' },
      { id: 's2', disease: 'Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B', vaccine: 'Infanrix hexa', date: '2016-08-16', dose: '2/3', manufacturer: 'GlaxoSmithKline', batch: 'IH1608', route: 'i.m.', site: 'Oberschenkel rechts' },
      { id: 's3', disease: 'Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B', vaccine: 'Infanrix hexa', date: '2017-02-20', dose: '3/3', manufacturer: 'GlaxoSmithKline', batch: 'IH1702', route: 'i.m.', site: 'Oberschenkel links' },
      { id: 's4', disease: 'Pneumokokken', vaccine: 'Prevenar 13', date: '2016-06-14', dose: '1/3', manufacturer: 'Pfizer', batch: 'PV1606', route: 'i.m.', site: 'Oberschenkel rechts' },
      { id: 's5', disease: 'Pneumokokken', vaccine: 'Prevenar 13', date: '2016-08-16', dose: '2/3', manufacturer: 'Pfizer', batch: 'PV1608', route: 'i.m.', site: 'Oberschenkel links' },
      { id: 's6', disease: 'Pneumokokken', vaccine: 'Prevenar 13', date: '2017-02-20', dose: '3/3', manufacturer: 'Pfizer', batch: 'PV1702', route: 'i.m.', site: 'Oberschenkel rechts' },
      { id: 's7', disease: 'Masern, Mumps, Röteln', vaccine: 'Priorix', date: '2017-04-10', dose: '1/2', manufacturer: 'GlaxoSmithKline', batch: 'PR1704', route: 's.c.', site: 'Oberarm links' },
      { id: 's8', disease: 'Masern, Mumps, Röteln', vaccine: 'Priorix', date: '2018-03-22', dose: '2/2', manufacturer: 'GlaxoSmithKline', batch: 'PR1803', route: 's.c.', site: 'Oberarm rechts' },
      { id: 's9', disease: 'Meningokokken C', vaccine: 'Menjugate', date: '2017-05-08', dose: '1/1', manufacturer: 'GlaxoSmithKline', batch: 'MJ1705', route: 'i.m.', site: 'Oberarm links' },
      { id: 's10', disease: 'Diphtherie, Tetanus, Pertussis, Polio', vaccine: 'Boostrix Polio', date: '2021-05-12', dose: 'Booster', manufacturer: 'GlaxoSmithKline', batch: 'BP2105', route: 'i.m.', site: 'Oberarm links' },
    ],
  },
  {
    id: 'M-daughter',
    firstName: 'Mia',
    lastName: 'Schmid',
    dob: '2020-09-15',
    sex: 'F',
    relation: 'daughter',
    vaccinations: [
      { id: 'd1', disease: 'Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B', vaccine: 'Infanrix hexa', date: '2020-11-20', dose: '1/3', manufacturer: 'GlaxoSmithKline', batch: 'IH2011', route: 'i.m.', site: 'Oberschenkel links' },
      { id: 'd2', disease: 'Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B', vaccine: 'Infanrix hexa', date: '2021-01-22', dose: '2/3', manufacturer: 'GlaxoSmithKline', batch: 'IH2101', route: 'i.m.', site: 'Oberschenkel rechts' },
      { id: 'd3', disease: 'Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B', vaccine: 'Infanrix hexa', date: '2021-07-16', dose: '3/3', manufacturer: 'GlaxoSmithKline', batch: 'IH2107', route: 'i.m.', site: 'Oberschenkel links' },
      { id: 'd4', disease: 'Pneumokokken', vaccine: 'Prevenar 13', date: '2020-11-20', dose: '1/3', manufacturer: 'Pfizer', batch: 'PV2011', route: 'i.m.', site: 'Oberschenkel rechts' },
      { id: 'd5', disease: 'Pneumokokken', vaccine: 'Prevenar 13', date: '2021-01-22', dose: '2/3', manufacturer: 'Pfizer', batch: 'PV2101', route: 'i.m.', site: 'Oberschenkel links' },
      { id: 'd6', disease: 'Pneumokokken', vaccine: 'Prevenar 13', date: '2021-07-16', dose: '3/3', manufacturer: 'Pfizer', batch: 'PV2107', route: 'i.m.', site: 'Oberschenkel rechts' },
      { id: 'd7', disease: 'Masern, Mumps, Röteln', vaccine: 'Priorix', date: '2021-09-18', dose: '1/2', manufacturer: 'GlaxoSmithKline', batch: 'PR2109', route: 's.c.', site: 'Oberarm links' },
      { id: 'd8', disease: 'Masern, Mumps, Röteln', vaccine: 'Priorix', date: '2022-08-24', dose: '2/2', manufacturer: 'GlaxoSmithKline', batch: 'PR2208', route: 's.c.', site: 'Oberarm rechts' },
      { id: 'd9', disease: 'Meningokokken B', vaccine: 'Bexsero', date: '2021-03-10', dose: '1/2', manufacturer: 'GlaxoSmithKline', batch: 'BX2103', route: 'i.m.', site: 'Oberschenkel links', note: 'Empfehlung Säuglinge' },
      { id: 'd10', disease: 'Meningokokken B', vaccine: 'Bexsero', date: '2021-09-18', dose: '2/2', manufacturer: 'GlaxoSmithKline', batch: 'BX2109', route: 'i.m.', site: 'Oberschenkel rechts', note: 'Empfehlung Säuglinge' },
    ],
  },
];
