ktor {
    deployment {
        port = 8888
        port = ${?PORT}
    }
    application {
        modules = [ ch.vacd.platform.ApplicationKt.module ]
    }
}

platform {
    fhirServer1Url = "http://fhir-server-1:9111/ch-vacd-api-reference-server/fhir"
    fhirServer1Url = ${?FHIR_SERVER_1_URL}
    mapperUrl = "http://openfhir:8083"
    mapperUrl = ${?MAPPER_URL}
    cdrUrl = "http://ehrbase:8080/ehrbase/rest/openehr/v1"
    cdrUrl = ${?CDR_URL}
    cdrUser = "ehrbase-user"
    cdrUser = ${?CDR_USER}
    cdrPass = "SuperSecretPassword"
    cdrPass = ${?CDR_PASS}
    templateId = "ch-vacd-immunization administration.v1-alpha"
    templateId = ${?TEMPLATE_ID}
}
