// Mock data for Impfdossier CH

const doctor = {
  name: "Dr. med. Sarah Müller",
  title: "Fachärztin Allgemeine Innere Medizin FMH",
  gln: "7601000123456",
  praxis: "Hausarztpraxis Bahnhofstrasse",
  address: "Bahnhofstrasse 47, 8001 Zürich",
  initials: "SM",
};

const patients = [
  {
    id: "P-1042",
    firstName: "Anna",
    lastName: "Schmid",
    dob: "1985-03-12",
    sex: "F",
    address: "Bahnhofstrasse 23, 8001 Zürich",
    email: "anna.schmid@bluewin.ch",
    phone: "+41 79 234 56 78",
    ahv: "756.1234.5678.90",
  },
  {
    id: "P-1043",
    firstName: "Marco",
    lastName: "Rossi",
    dob: "1978-11-04",
    sex: "M",
    address: "Via Nassa 5, 6900 Lugano",
    email: "m.rossi@gmail.com",
    phone: "+41 76 123 45 67",
    ahv: "756.2345.6789.01",
  },
  {
    id: "P-1044",
    firstName: "Sophie",
    lastName: "Dubois",
    dob: "1992-06-22",
    sex: "F",
    address: "Rue du Mont-Blanc 12, 1201 Genève",
    email: "sophie.dubois@bluemail.ch",
    phone: "+41 78 567 89 12",
    ahv: "756.3456.7890.12",
  },
  {
    id: "P-1045",
    firstName: "Lukas",
    lastName: "Meier",
    dob: "2010-09-15",
    sex: "M",
    address: "Marktgasse 8, 3011 Bern",
    email: "familie.meier@hispeed.ch",
    phone: "+41 79 345 67 89",
    ahv: "756.4567.8901.23",
  },
  {
    id: "P-1046",
    firstName: "Elena",
    lastName: "Weber",
    dob: "1965-04-30",
    sex: "F",
    address: "Seestrasse 142, 6004 Luzern",
    email: "e.weber@swissonline.ch",
    phone: "+41 76 789 01 23",
    ahv: "756.5678.9012.34",
  },
  {
    id: "P-1047",
    firstName: "Noah",
    lastName: "Brunner",
    dob: "2018-12-03",
    sex: "M",
    address: "Hauptstrasse 45, 8400 Winterthur",
    email: "eltern.brunner@hotmail.com",
    phone: "+41 79 456 78 90",
    ahv: "756.6789.0123.45",
  },
  {
    id: "P-1048",
    firstName: "Léa",
    lastName: "Favre",
    dob: "1989-07-18",
    sex: "F",
    address: "Avenue de la Gare 7, 1003 Lausanne",
    email: "lea.favre@bluewin.ch",
    phone: "+41 78 901 23 45",
    ahv: "756.7890.1234.56",
  },
  {
    id: "P-1049",
    firstName: "Stefan",
    lastName: "Huber",
    dob: "1972-02-09",
    sex: "M",
    address: "Dorfstrasse 19, 4051 Basel",
    email: "s.huber@gmx.ch",
    phone: "+41 76 234 56 78",
    ahv: "756.8901.2345.67",
  },
  {
    id: "P-1050",
    firstName: "Maya",
    lastName: "Stadler",
    dob: "1995-10-27",
    sex: "F",
    address: "Limmatquai 88, 8001 Zürich",
    email: "maya.stadler@protonmail.ch",
    phone: "+41 79 678 90 12",
    ahv: "756.9012.3456.78",
  },
  {
    id: "P-1051",
    firstName: "Jonas",
    lastName: "Keller",
    dob: "2003-05-14",
    sex: "M",
    address: "Spitalgasse 11, 3011 Bern",
    email: "j.keller@student.ch",
    phone: "+41 76 345 67 89",
    ahv: "756.0123.4567.89",
  },
];

// Vaccination records keyed by patient id.
// Grouped semantically by targetDisease; flat array — group in UI.
// Schema follows Swiss Impfausweis / FHIR Immunization.
const vaccinations = {
  "P-1042": [
    { id: "V1", disease: "Diphtherie, Tetanus, Pertussis, Polio", vaccine: "Infanrix-IPV", date: "1985-05-14", dose: "1/4", batch: "A4523B", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel links" },
    { id: "V2", disease: "Diphtherie, Tetanus, Pertussis, Polio", vaccine: "Infanrix-IPV", date: "1985-07-22", dose: "2/4", batch: "A4612C", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V3", disease: "Diphtherie, Tetanus, Pertussis, Polio", vaccine: "Infanrix-IPV", date: "1986-03-10", dose: "3/4", batch: "B1023K", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel links" },
    { id: "V4", disease: "Diphtherie, Tetanus, Pertussis, Polio", vaccine: "Boostrix Polio", date: "1990-09-08", dose: "Booster", batch: "C8821L", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V5", disease: "Diphtherie, Tetanus, Pertussis", vaccine: "Boostrix", date: "2015-11-04", dose: "Booster", batch: "DT9923", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V6", disease: "Masern, Mumps, Röteln", vaccine: "MMR-VaxPro", date: "1986-04-18", dose: "1/2", batch: "M2204X", manufacturer: "MSD", route: "s.c.", site: "Oberarm rechts" },
    { id: "V7", disease: "Masern, Mumps, Röteln", vaccine: "MMR-VaxPro", date: "1992-08-25", dose: "2/2", batch: "M5511Y", manufacturer: "MSD", route: "s.c.", site: "Oberarm rechts" },
    { id: "V8", disease: "Hepatitis B", vaccine: "Engerix-B", date: "1998-01-12", dose: "1/3", batch: "HB1201", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V9", disease: "Hepatitis B", vaccine: "Engerix-B", date: "1998-02-15", dose: "2/3", batch: "HB1245", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V10", disease: "Hepatitis B", vaccine: "Engerix-B", date: "1998-08-10", dose: "3/3", batch: "HB1502", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm rechts" },
    { id: "V11", disease: "FSME", vaccine: "FSME-Immun CC", date: "2012-04-02", dose: "1/3", batch: "FS3301", manufacturer: "Pfizer", route: "i.m.", site: "Oberarm links" },
    { id: "V12", disease: "FSME", vaccine: "FSME-Immun CC", date: "2012-05-30", dose: "2/3", batch: "FS3344", manufacturer: "Pfizer", route: "i.m.", site: "Oberarm links" },
    { id: "V13", disease: "FSME", vaccine: "FSME-Immun CC", date: "2013-03-12", dose: "3/3", batch: "FS4012", manufacturer: "Pfizer", route: "i.m.", site: "Oberarm links" },
    { id: "V14", disease: "FSME", vaccine: "FSME-Immun CC", date: "2023-04-19", dose: "Booster", batch: "FS9912", manufacturer: "Pfizer", route: "i.m.", site: "Oberarm links" },
    { id: "V15", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-05-21", dose: "1/2", batch: "EW0150", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V16", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-06-18", dose: "2/2", batch: "FA2421", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V17", disease: "COVID-19", vaccine: "Comirnaty Omicron XBB.1.5", date: "2023-10-12", dose: "Booster", batch: "GH8821", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm rechts" },
    { id: "V18", disease: "Influenza (saisonal)", vaccine: "Fluarix Tetra", date: "2023-10-12", dose: "Saison 23/24", batch: "FLU2324", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V19", disease: "Influenza (saisonal)", vaccine: "Fluarix Tetra", date: "2024-10-08", dose: "Saison 24/25", batch: "FLU2425", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V20", disease: "Influenza (saisonal)", vaccine: "Fluarix Tetra", date: "2025-10-14", dose: "Saison 25/26", batch: "FLU2526", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1043": [
    { id: "V1", disease: "Diphtherie, Tetanus, Pertussis", vaccine: "Boostrix", date: "2018-06-12", dose: "Booster", batch: "BT2018A", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V2", disease: "Hepatitis A + B", vaccine: "Twinrix", date: "2019-02-04", dose: "1/3", batch: "TW1901", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm rechts" },
    { id: "V3", disease: "Hepatitis A + B", vaccine: "Twinrix", date: "2019-03-08", dose: "2/3", batch: "TW1907", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm rechts" },
    { id: "V4", disease: "Hepatitis A + B", vaccine: "Twinrix", date: "2019-09-15", dose: "3/3", batch: "TW1942", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V5", disease: "COVID-19", vaccine: "Spikevax (mRNA-1273)", date: "2021-07-02", dose: "1/2", batch: "MR5512", manufacturer: "Moderna", route: "i.m.", site: "Oberarm links" },
    { id: "V6", disease: "COVID-19", vaccine: "Spikevax (mRNA-1273)", date: "2021-08-04", dose: "2/2", batch: "MR5598", manufacturer: "Moderna", route: "i.m.", site: "Oberarm links" },
    { id: "V7", disease: "Influenza (saisonal)", vaccine: "Influvac Tetra", date: "2024-11-03", dose: "Saison 24/25", batch: "IV2425", manufacturer: "Viatris", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1044": [
    { id: "V1", disease: "Masern, Mumps, Röteln", vaccine: "Priorix", date: "1993-09-14", dose: "1/2", batch: "PR9314", manufacturer: "GlaxoSmithKline", route: "s.c.", site: "Oberarm links" },
    { id: "V2", disease: "Masern, Mumps, Röteln", vaccine: "Priorix", date: "1998-04-22", dose: "2/2", batch: "PR9822", manufacturer: "GlaxoSmithKline", route: "s.c.", site: "Oberarm rechts" },
    { id: "V3", disease: "HPV", vaccine: "Gardasil 9", date: "2010-08-15", dose: "1/2", batch: "GD1015", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V4", disease: "HPV", vaccine: "Gardasil 9", date: "2011-02-20", dose: "2/2", batch: "GD1120", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V5", disease: "Diphtherie, Tetanus, Pertussis", vaccine: "Boostrix", date: "2022-05-30", dose: "Booster", batch: "BX2230", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V6", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-06-15", dose: "1/2", batch: "EW0322", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm rechts" },
    { id: "V7", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-07-13", dose: "2/2", batch: "EW0455", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm rechts" },
  ],
  "P-1045": [
    { id: "V1", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B", vaccine: "Infanrix hexa", date: "2011-01-20", dose: "1/3", batch: "IH1101", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel links" },
    { id: "V2", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B", vaccine: "Infanrix hexa", date: "2011-03-22", dose: "2/3", batch: "IH1108", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V3", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B", vaccine: "Infanrix hexa", date: "2011-09-18", dose: "3/3", batch: "IH1135", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel links" },
    { id: "V4", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2011-01-20", dose: "1/3", batch: "PV1101", manufacturer: "Pfizer", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V5", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2011-03-22", dose: "2/3", batch: "PV1110", manufacturer: "Pfizer", route: "i.m.", site: "Oberschenkel links" },
    { id: "V6", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2011-09-18", dose: "3/3", batch: "PV1141", manufacturer: "Pfizer", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V7", disease: "Masern, Mumps, Röteln", vaccine: "MMR-VaxPro", date: "2011-10-14", dose: "1/2", batch: "MM1110", manufacturer: "MSD", route: "s.c.", site: "Oberarm links" },
    { id: "V8", disease: "Masern, Mumps, Röteln", vaccine: "MMR-VaxPro", date: "2012-09-22", dose: "2/2", batch: "MM1212", manufacturer: "MSD", route: "s.c.", site: "Oberarm rechts" },
    { id: "V9", disease: "HPV", vaccine: "Gardasil 9", date: "2021-04-12", dose: "1/2", batch: "GD2104", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V10", disease: "HPV", vaccine: "Gardasil 9", date: "2021-10-08", dose: "2/2", batch: "GD2110", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V11", disease: "Diphtherie, Tetanus, Pertussis, Polio", vaccine: "Boostrix Polio", date: "2024-08-19", dose: "Booster", batch: "BP2408", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1046": [
    { id: "V1", disease: "Diphtherie, Tetanus", vaccine: "Td-pur", date: "2005-11-12", dose: "Booster", batch: "TD0511", manufacturer: "GSK", route: "i.m.", site: "Oberarm links" },
    { id: "V2", disease: "Diphtherie, Tetanus, Pertussis", vaccine: "Boostrix", date: "2015-10-08", dose: "Booster", batch: "BX1510", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm rechts" },
    { id: "V3", disease: "Herpes Zoster", vaccine: "Shingrix", date: "2022-03-18", dose: "1/2", batch: "SH2203", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V4", disease: "Herpes Zoster", vaccine: "Shingrix", date: "2022-06-20", dose: "2/2", batch: "SH2206", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V5", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2023-09-05", dose: "1/1", batch: "PV2309", manufacturer: "Pfizer", route: "i.m.", site: "Oberarm rechts" },
    { id: "V6", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-03-22", dose: "1/2", batch: "EJ6789", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V7", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-04-19", dose: "2/2", batch: "EJ6912", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V8", disease: "COVID-19", vaccine: "Comirnaty Omicron XBB.1.5", date: "2024-10-22", dose: "Booster", batch: "GH9234", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm rechts" },
    { id: "V9", disease: "Influenza (saisonal)", vaccine: "Efluelda (HD)", date: "2024-10-22", dose: "Saison 24/25", batch: "EF2425", manufacturer: "Sanofi", route: "i.m.", site: "Oberarm links" },
    { id: "V10", disease: "Influenza (saisonal)", vaccine: "Efluelda (HD)", date: "2025-10-20", dose: "Saison 25/26", batch: "EF2526", manufacturer: "Sanofi", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1047": [
    { id: "V1", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B", vaccine: "Infanrix hexa", date: "2019-02-15", dose: "1/3", batch: "IH1902", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel links" },
    { id: "V2", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B", vaccine: "Infanrix hexa", date: "2019-04-12", dose: "2/3", batch: "IH1908", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V3", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib, Hepatitis B", vaccine: "Infanrix hexa", date: "2019-12-08", dose: "3/3", batch: "IH1948", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberschenkel links" },
    { id: "V4", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2019-02-15", dose: "1/3", batch: "PV1902", manufacturer: "Pfizer", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V5", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2019-04-12", dose: "2/3", batch: "PV1909", manufacturer: "Pfizer", route: "i.m.", site: "Oberschenkel links" },
    { id: "V6", disease: "Pneumokokken", vaccine: "Prevenar 13", date: "2019-12-08", dose: "3/3", batch: "PV1949", manufacturer: "Pfizer", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V7", disease: "Masern, Mumps, Röteln", vaccine: "Priorix", date: "2020-01-22", dose: "1/2", batch: "PR2001", manufacturer: "GlaxoSmithKline", route: "s.c.", site: "Oberarm links" },
    { id: "V8", disease: "Masern, Mumps, Röteln", vaccine: "Priorix", date: "2021-02-04", dose: "2/2", batch: "PR2102", manufacturer: "GlaxoSmithKline", route: "s.c.", site: "Oberarm rechts" },
  ],
  "P-1048": [
    { id: "V1", disease: "Diphtherie, Tetanus, Pertussis", vaccine: "Boostrix", date: "2009-04-12", dose: "Booster", batch: "BX0904", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V2", disease: "HPV", vaccine: "Gardasil", date: "2008-09-10", dose: "1/3", batch: "GD0809", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V3", disease: "HPV", vaccine: "Gardasil", date: "2008-11-18", dose: "2/3", batch: "GD0811", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V4", disease: "HPV", vaccine: "Gardasil", date: "2009-04-12", dose: "3/3", batch: "GD0904", manufacturer: "MSD", route: "i.m.", site: "Oberarm rechts" },
    { id: "V5", disease: "Gelbfieber", vaccine: "Stamaril", date: "2018-06-04", dose: "1/1", batch: "SM1806", manufacturer: "Sanofi", route: "s.c.", site: "Oberarm links", note: "Reisemedizin — Afrika" },
    { id: "V6", disease: "Tollwut", vaccine: "Rabipur", date: "2018-06-04", dose: "1/3", batch: "RB1806", manufacturer: "Bavarian Nordic", route: "i.m.", site: "Oberarm rechts" },
    { id: "V7", disease: "Tollwut", vaccine: "Rabipur", date: "2018-06-11", dose: "2/3", batch: "RB1811", manufacturer: "Bavarian Nordic", route: "i.m.", site: "Oberarm rechts" },
    { id: "V8", disease: "Tollwut", vaccine: "Rabipur", date: "2018-06-25", dose: "3/3", batch: "RB1825", manufacturer: "Bavarian Nordic", route: "i.m.", site: "Oberarm links" },
    { id: "V9", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-08-12", dose: "1/2", batch: "FA4567", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V10", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-09-09", dose: "2/2", batch: "FA4823", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1049": [
    { id: "V1", disease: "Diphtherie, Tetanus", vaccine: "Td-pur", date: "2012-05-18", dose: "Booster", batch: "TD1205", manufacturer: "GSK", route: "i.m.", site: "Oberarm rechts" },
    { id: "V2", disease: "FSME", vaccine: "Encepur", date: "2015-03-08", dose: "1/3", batch: "EC1503", manufacturer: "Bavarian Nordic", route: "i.m.", site: "Oberarm links" },
    { id: "V3", disease: "FSME", vaccine: "Encepur", date: "2015-04-22", dose: "2/3", batch: "EC1504", manufacturer: "Bavarian Nordic", route: "i.m.", site: "Oberarm links" },
    { id: "V4", disease: "FSME", vaccine: "Encepur", date: "2016-02-15", dose: "3/3", batch: "EC1602", manufacturer: "Bavarian Nordic", route: "i.m.", site: "Oberarm links" },
    { id: "V5", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-04-08", dose: "1/2", batch: "ER8801", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V6", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-05-06", dose: "2/2", batch: "ER8922", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1050": [
    { id: "V1", disease: "Masern, Mumps, Röteln", vaccine: "Priorix", date: "1996-10-12", dose: "1/2", batch: "PR9610", manufacturer: "GlaxoSmithKline", route: "s.c.", site: "Oberarm links" },
    { id: "V2", disease: "Masern, Mumps, Röteln", vaccine: "Priorix", date: "2001-08-22", dose: "2/2", batch: "PR0108", manufacturer: "GlaxoSmithKline", route: "s.c.", site: "Oberarm rechts" },
    { id: "V3", disease: "HPV", vaccine: "Gardasil 9", date: "2014-05-12", dose: "1/2", batch: "GD1405", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V4", disease: "HPV", vaccine: "Gardasil 9", date: "2014-11-04", dose: "2/2", batch: "GD1411", manufacturer: "MSD", route: "i.m.", site: "Oberarm links" },
    { id: "V5", disease: "Diphtherie, Tetanus, Pertussis", vaccine: "Boostrix", date: "2020-06-15", dose: "Booster", batch: "BX2006", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm rechts" },
    { id: "V6", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-09-14", dose: "1/2", batch: "GA1144", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
    { id: "V7", disease: "COVID-19", vaccine: "Comirnaty (BNT162b2)", date: "2021-10-12", dose: "2/2", batch: "GA1201", manufacturer: "Pfizer-BioNTech", route: "i.m.", site: "Oberarm links" },
  ],
  "P-1051": [
    { id: "V1", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib", vaccine: "Pentavac", date: "2003-07-18", dose: "1/3", batch: "PV0307", manufacturer: "Sanofi", route: "i.m.", site: "Oberschenkel links" },
    { id: "V2", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib", vaccine: "Pentavac", date: "2003-09-22", dose: "2/3", batch: "PV0309", manufacturer: "Sanofi", route: "i.m.", site: "Oberschenkel rechts" },
    { id: "V3", disease: "Diphtherie, Tetanus, Pertussis, Polio, Hib", vaccine: "Pentavac", date: "2004-05-10", dose: "3/3", batch: "PV0405", manufacturer: "Sanofi", route: "i.m.", site: "Oberschenkel links" },
    { id: "V4", disease: "Masern, Mumps, Röteln", vaccine: "MMR-VaxPro", date: "2004-08-15", dose: "1/2", batch: "MM0408", manufacturer: "MSD", route: "s.c.", site: "Oberarm links" },
    { id: "V5", disease: "Masern, Mumps, Röteln", vaccine: "MMR-VaxPro", date: "2009-06-22", dose: "2/2", batch: "MM0906", manufacturer: "MSD", route: "s.c.", site: "Oberarm rechts" },
    { id: "V6", disease: "Meningokokken ACWY", vaccine: "Menveo", date: "2018-08-12", dose: "1/1", batch: "MV1808", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm links" },
    { id: "V7", disease: "Diphtherie, Tetanus, Pertussis, Polio", vaccine: "Boostrix Polio", date: "2017-11-14", dose: "Booster", batch: "BP1711", manufacturer: "GlaxoSmithKline", route: "i.m.", site: "Oberarm rechts" },
    { id: "V8", disease: "COVID-19", vaccine: "Spikevax (mRNA-1273)", date: "2021-12-08", dose: "1/2", batch: "MR8821", manufacturer: "Moderna", route: "i.m.", site: "Oberarm links" },
    { id: "V9", disease: "COVID-19", vaccine: "Spikevax (mRNA-1273)", date: "2022-01-12", dose: "2/2", batch: "MR8901", manufacturer: "Moderna", route: "i.m.", site: "Oberarm links" },
  ],
};

// Catalog used in form dropdowns
const vaccineCatalog = [
  "Boostrix",
  "Boostrix Polio",
  "Comirnaty (BNT162b2)",
  "Comirnaty Omicron XBB.1.5",
  "Efluelda (HD)",
  "Encepur",
  "Engerix-B",
  "FSME-Immun CC",
  "Fluarix Tetra",
  "Gardasil 9",
  "Havrix 1440",
  "Influvac Tetra",
  "Infanrix-IPV",
  "Infanrix hexa",
  "Menveo",
  "MMR-VaxPro",
  "Nimenrix",
  "Pentavac",
  "Prevenar 13",
  "Priorix",
  "Rabipur",
  "Shingrix",
  "Spikevax (mRNA-1273)",
  "Stamaril",
  "Td-pur",
  "Twinrix",
  "Varilrix",
];

const manufacturers = [
  "Bavarian Nordic",
  "GlaxoSmithKline",
  "Moderna",
  "MSD",
  "Pfizer",
  "Pfizer-BioNTech",
  "Sanofi",
  "Viatris",
];

const routes = [
  { value: "i.m.", label: "i.m. (intramuskulär)" },
  { value: "s.c.", label: "s.c. (subkutan)" },
  { value: "i.d.", label: "i.d. (intradermal)" },
  { value: "oral", label: "oral" },
  { value: "nasal", label: "nasal" },
];

const sites = [
  "Oberarm links (M. deltoideus)",
  "Oberarm rechts (M. deltoideus)",
  "Oberschenkel links (M. vastus lateralis)",
  "Oberschenkel rechts (M. vastus lateralis)",
  "Gesäss links",
  "Gesäss rechts",
];

const reasons = [
  "Grundimmunisierung",
  "Auffrischimpfung (Booster)",
  "Nachholimpfung",
  "Reiseimpfung",
  "Risikogruppe — beruflich",
  "Risikogruppe — medizinisch",
  "Postexpositionsprophylaxe",
  "Saisonale Impfung",
];

window.AppData = { doctor, patients, vaccinations, vaccineCatalog, manufacturers, routes, sites, reasons };
